### ISSUE TITLE
Extra speed

### ISSUE THREAD

**Issue by JackPlaysGames0510** [PoomSmart/YouSpeed#1]
Can you make it compatible for the extra speed

**Comment by PoomSmart** [comment]
Are you talking about YTSpeed tweak (not YouSpeed)?

**Comment by JackPlaysGames0510** [comment]
Yeah that yt light has built-in

**Comment by PoomSmart** [comment]
You can install YTSpeed then. 😉
Isn't it already compatible?

**Comment by JackPlaysGames0510** [comment]
yeah but can you make it so you can get the extra speed option on the overlay

**Comment by PoomSmart** [comment]
Not sure what you are talking about? It's already working.

![IMG_0211](https://github.com/user-attachments/assets/8501831d-cef0-4502-a275-006a9f633526)

**Comment by JackPlaysGames0510** [comment]
maybe i didn't relise it was a scrolling thing

**Comment by JackPlaysGames0510** [comment]
https://github.com/user-attachments/assets/6811fce1-a2ff-49a9-b84c-fe6507d59f56

**Comment by PoomSmart** [comment]
I see, this is iPhone thing. I'll see if I can modify YTSpeed to work with this.

**Comment by JackPlaysGames0510** [comment]
that's cool but its built-in yt light
