### ISSUE TITLE
How to use YouSpeed

### ISSUE THREAD

**Issue by gmanc2** [PoomSmart/YouSpeed#3]
I just installed the latest commit of uYouPlus but don't see anywhere to enable or use YouSpeed. The plus and minus playback speed buttons don't work still. 

Version
19.42.1-3.0.4

hidePlayNextInQueue_enabled: 1
googleSigninFix_enabled: 0
showedWelcomeVC: 1
relatedVideosAtTheEndOfYTVideos: 1
removeYouTubeAds: 0
disableAgeRestriction: 0
shortsProgressBar: 1

**Comment by PoomSmart** [comment]
https://www.idownloadblog.com/2024/12/16/youspeed-poomsmart/
