### ISSUE TITLE
Does not show up in settings

### ISSUE THREAD

**Issue by gmanc2** [PoomSmart/YouSpeed#4]
I installed the latest version of uYouPlus and the setting to activate it does not show up in Video Overlay.![image](https://github.com/user-attachments/assets/6b814e3c-cb40-4c20-a10d-4ddd01d1a00a)

uYou 3.0.4 (most recent commit as of today)
YouTube version 19.42.1

**Comment by PoomSmart** [comment]
Open the issue on uYouPlus repo, not here.
